basePath: /api/v1
definitions:
  app.ResponseDTO:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8001
info:
  contact:
    email: murtaza896@gmail.com
    name: Murtaza Sadriwala
  description: This is a authentication/authorization service.
  title: Auth Microservice API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.ResponseDTO'
      tags:
      - health
swagger: "2.0"
